version: '2'

services:
  app:
    image: 'sport-buddy-finder:latest'
    ports:
      - "8080:8080"
    build:
      context: docker
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sportbuddy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD= /my_secret.txt
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:16.1-alpine3.18'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= /my_secret.txt
      - POSTGRES_DB=sportbuddy
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql
  db-init:
    image: 'postgres:16.1-alpine3.18'
    depends_on:
      - db
    entrypoint: ["sh", "-c", "sleep 10 && psql -h db -U docker -f docker-entrypoint-initdb.d/import.sql"]

  frontend:
    image: 'frontend:latest'
    container_name: frontend
    depends_on:
      - app
    ports:
      - "3000:3000"