INSERT INTO SPORT (sport_id, NAME) VALUES (1, 'Football');
INSERT INTO SPORT (sport_id, NAME) VALUES (2, 'Basketball');
INSERT INTO SPORT (sport_id, NAME) VALUES (3, 'Tennis');
INSERT INTO SPORT (sport_id, NAME) VALUES (4, 'Golf');
INSERT INTO SPORT (sport_id, NAME) VALUES (5, 'Swimming');
INSERT INTO SPORT (sport_id, NAME) VALUES (6, 'Baseball');
INSERT INTO SPORT (sport_id, NAME) VALUES (7, 'Hiking');
INSERT INTO SPORT (sport_id, NAME) VALUES (8, 'Volleyball');
INSERT INTO SPORT (sport_id, NAME) VALUES (9, 'Table tennis');
INSERT INTO SPORT (sport_id, NAME) VALUES (10, 'Badminton');
INSERT INTO SPORT (sport_id, NAME) VALUES (11, 'Rugby');
INSERT INTO SPORT (sport_id, NAME) VALUES (12, 'Cricket');
INSERT INTO SPORT (sport_id, NAME) VALUES (13, 'Hockey');
INSERT INTO SPORT (sport_id, NAME) VALUES (14, 'Cycling');
INSERT INTO SPORT (sport_id, NAME) VALUES (15, 'Athletics');
INSERT INTO SPORT (sport_id, NAME) VALUES (16, 'Boxing');
INSERT INTO SPORT (sport_id, NAME) VALUES (17, 'Wrestling');
INSERT INTO SPORT (sport_id, NAME) VALUES (18, 'Skiing');
INSERT INTO SPORT (sport_id, NAME) VALUES (19, 'Snowboarding');
INSERT INTO SPORT (sport_id, NAME) VALUES (20, 'Ice skating');
INSERT INTO SPORT (sport_id, NAME) VALUES (21, 'Gymnastics');
INSERT INTO SPORT (sport_id, NAME) VALUES (22, 'Rock climbing');
INSERT INTO SPORT (sport_id, NAME) VALUES (23, 'Yoga');
INSERT INTO APP_USER (id, birth_date,email,name,password,profile_picurl) VALUES (1,'1996-10-10','ex@gmail.com','Johny','123','http://vlmi');

